
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: cfb894ff0eewef03d602
            clientSecret: 4b23c8e09b1d86a927af3a9dfc5487644a4f420c

          google:
            clientId: 713580270-tee25sbific2lpv4doaar8kvk6ajvh.apps.googleusercontent.com
            clientSecret: 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
